name: Build and Push Docker image
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    # - name: Install jq
    #   run: sudo apt-get install -y jq

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build, Tag, and Push the Image to Docker Hub
      id: build-image
      env:
        IMAGE_TAG: latest
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/my-go-app:$IMAGE_TAG .
        docker push ${{ secrets.DOCKER_USERNAME }}/my-go-app:$IMAGE_TAG
